### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/Latency-Predictor#2]
This repository has no license file.

If you extend TVM to implement Latency Predictor, you must specify your license referring to TVM's license.

[TVM seems to use "Apache 2.0" License.](https://github.com/apache/incubator-tvm/blob/master/LICENSE)

I think that Apache 2.0 license is proper for this repository.

**Comment by hoseung2** [comment]
Updated.

**Comment by LeeHayun** [comment]
This issue has been resolved.
So, I close this issue.
