### ISSUE TITLE
'XGBoostCostModel' object has no object 'pool'

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/Latency-Predictor#3]
Hi,
I installed requirements and now try to run test codes.

When I run test.py, this error message occurs and running fails.
```
AttributeError: 'XGBoostCostModel' object has no attribute 'pool'
```
My Environment is ubuntu18.04 and NVIDIA GPU.

Can you tell me how to fix this?

**Comment by hoseung2** [comment]
I think you didn't install XGBoost.

You can install with
```
pip install xgboost
```
