### ISSUE TITLE
Cannot find config

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/Latency-Predictor#4]
When I run a model including a 1x1 convolution layer on cuda, it warns me of possible performance degradation.

![image](https://user-images.githubusercontent.com/37430923/69610247-bf4a8380-106e-11ea-9c77-f36e60114fa6.png)

How can I make this layer find proper configuration?

**Comment by hoseung2** [comment]
You must specify your device, like -model=tx2, -model=1080ti.
