### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/Latency-Predictor#5]
When I run test.py with model=nvidia using RPC to work on odroid-xu4, it generates error as following.

TVMError: Socket SockChannel::Send Error:Broken pipe
![image](https://user-images.githubusercontent.com/37430923/69624536-37717300-1088-11ea-961f-2673a215bdc1.png)

It seems this error have something to do with parameters but I cannot find why.
What would be wrong?

**Comment by hoseung2** [comment]
If the send time is too long, the connection can be reset. 

Maybe you can fix this making model more lightly.
