### ISSUE TITLE
How the predictor predicts latency

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/Latency-Predictor#6]
Hi,
I want to ask how the predictor will predict the latency of a DNN model. 
By machine learning or some other method?
And how many and what kinds of factors do you think counts to predict latency now?

**Comment by hoseung2** [comment]
It is currently under development.

We may consider some hardware factors like cache size, a number of cores and model factors input size, operations.

It'll predict latency using the regression model, but we will also consider the direction to use DNN.
